name: Auto Build Docker

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    uses: XenosLu/image/.github/workflows/build.yml@master
    with:
      username: xenocider
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}
